version: '3.8'
services:
  clicket-frontend:
    image: registrycbbadev.et.bo/clicket/clicket-frontend:etr
    container_name: clicket-frontend
    ports:
      - "9042:80"
    networks:
      - et-clicket-etr-net
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role==worker]
    volumes:
      - /etc/localtime:/etc/localtime:ro
networks:
  et-clicket-etr-net:
    external: true
